nav:
- Home: index.md
- BETA: 
  - Beta/README.md
  - glob: "Beta/*.md"
- BetaDEV:
  - BetaDEV/README.md
  - glob: "BetaDEV/*.md"
- BetaSEC:
  - BetaSEC/README.md
  - "BetaSEC/*"
- BetaLAN:
  - BetaLAN/README.md
  - "BetaLAN/*.md"
- Eventkom: 
  - Eventkom/README.md
  - "Eventkom/*.md"
- Bedkom: 
  - Bedkom/README.md
  - "Bedkom/*.md"