site_name: wiki.betauia.net
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
  font:
    text: Roboto
    code: Roboto Mono

extra_css:
  - css/theme.css

plugins:
- awesome-nav