flatten_single_child_section: true

ignore: "*.hidden.md"

nav:
- Home: index.md
- BETA:
  - "Beta/README.md"
  - "Beta/*.md"
- BetaDEV:
  - BetaDEV/README.md
  - "BetaDEV/*.md"
- BetaSEC:
  - BetaSEC/README.md
  - "BetaSEC/*.md"
- BetaLAN:
  - BetaLAN/README.md
  - "BetaLAN/*.md"
- Eventkom: 
  - Eventkom/README.md
  - "Eventkom/*.md"
- Bedkom:
  - Bedkom/README.md
  - "Bedkom/*.md"