name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - update/workflow

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v4

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.26
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # CUSTOM_DOMAIN: wiki.betauia.net
          CONFIG_FILE: mkdocs.yml
          REQUIREMENTS: requirements.txt

